"""GitHub platform adapter using httpx."""

from __future__ import annotations

import time

import httpx

from src.exceptions import (
    CommentWriteBackError,
    CredentialMissingError,
    PlatformAPIError,
)
from src.logger import get_logger
from src.models import PRInfo
from src.platform.base import PlatformAdapter

logger = get_logger(__name__)

_GITHUB_API_BASE = "https://api.github.com"
_MAX_RETRIES = 2
_RETRY_INTERVAL = 1  # seconds
_AI_COMMENT_IDENTIFIER = (
    "\n\n---\n"
    "🤖 *This review was auto-generated by "
    "PR Review AI.*"
)


class GitHubAdapter(PlatformAdapter):
    """Adapter for interacting with GitHub Pull Requests."""

    def __init__(
        self,
        token: str,
        owner: str,
        repo: str,
        pr_number: int,
    ) -> None:
        self.token = token
        self.owner = owner
        self.repo = repo
        self.pr_number = pr_number

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _headers(self) -> dict[str, str]:
        return {
            "Authorization": f"Bearer {self.token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        }

    def _request(
        self,
        method: str,
        url: str,
        *,
        headers: dict[str, str] | None = None,
        json: dict | None = None,
    ) -> httpx.Response:
        """Execute an HTTP request with retry on transient errors."""
        hdrs = headers or self._headers()
        last_exc: Exception | None = None

        for attempt in range(_MAX_RETRIES + 1):
            start = time.monotonic()
            try:
                resp = httpx.request(
                    method,
                    url,
                    headers=hdrs,
                    json=json,
                    timeout=30,
                    follow_redirects=True,
                )
                elapsed = time.monotonic() - start
                logger.info(
                    "GitHub API %s %s -> %s (%.2fs)",
                    method,
                    self._sanitize_url(url),
                    resp.status_code,
                    elapsed,
                )
                return resp
            except (
                httpx.TransportError,
                httpx.TimeoutException,
            ) as exc:
                elapsed = time.monotonic() - start
                last_exc = exc
                logger.warning(
                    "GitHub API %s %s failed "
                    "(attempt %d/%d, %.2fs): %s",
                    method,
                    self._sanitize_url(url),
                    attempt + 1,
                    _MAX_RETRIES + 1,
                    elapsed,
                    exc,
                )
                if attempt < _MAX_RETRIES:
                    time.sleep(_RETRY_INTERVAL)

        raise PlatformAPIError(
            f"GitHub API request failed after "
            f"{_MAX_RETRIES + 1} attempts: {last_exc}"
        )

    @staticmethod
    def _sanitize_url(url: str) -> str:
        """Return URL without query parameters."""
        return url.split("?")[0]

    def _check_credentials(self) -> None:
        if not self.token:
            raise CredentialMissingError(
                "GitHub token is not configured. "
                "Set the GITHUB_TOKEN environment variable."
            )

    def _handle_error_status(
        self, resp: httpx.Response, context: str
    ) -> None:
        """Raise PlatformAPIError for non-2xx responses."""
        if resp.is_success:
            return

        status = resp.status_code
        if status == 401:
            raise PlatformAPIError(
                f"GitHub API authentication failed "
                f"({context}). Verify your GITHUB_TOKEN "
                f"is valid and has the required scopes."
            )
        if status == 403:
            raise PlatformAPIError(
                f"GitHub API access forbidden ({context})."
                f" Your token may lack permissions or "
                f"you hit a rate limit."
            )
        if status == 404:
            raise PlatformAPIError(
                f"GitHub resource not found ({context})."
                f" Check that {self.owner}/{self.repo}"
                f" PR #{self.pr_number} exists."
            )
        raise PlatformAPIError(
            f"GitHub API error {status} ({context}): "
            f"{resp.text[:200]}"
        )

    # ------------------------------------------------------------------
    # Retry wrapper for 5xx responses
    # ------------------------------------------------------------------

    def _request_with_status_retry(
        self,
        method: str,
        url: str,
        *,
        headers: dict[str, str] | None = None,
        json: dict | None = None,
        context: str = "",
    ) -> httpx.Response:
        """Like _request but also retries on 5xx status codes."""
        hdrs = headers or self._headers()

        for attempt in range(_MAX_RETRIES + 1):
            resp = self._request(
                method, url, headers=hdrs, json=json
            )
            if resp.status_code < 500:
                return resp
            logger.warning(
                "GitHub API %s %s returned %s "
                "(attempt %d/%d)",
                method,
                self._sanitize_url(url),
                resp.status_code,
                attempt + 1,
                _MAX_RETRIES + 1,
            )
            if attempt < _MAX_RETRIES:
                time.sleep(_RETRY_INTERVAL)

        return resp  # type: ignore[possibly-undefined]

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    def fetch_pr_info(self, pr_url: str) -> PRInfo:
        """Fetch PR metadata and diff from GitHub."""
        self._check_credentials()

        pr_api_url = (
            f"{_GITHUB_API_BASE}/repos/"
            f"{self.owner}/{self.repo}"
            f"/pulls/{self.pr_number}"
        )

        # 1. Get PR metadata
        resp = self._request_with_status_retry(
            "GET", pr_api_url, context="fetch PR info"
        )
        self._handle_error_status(resp, "fetch PR info")
        data = resp.json()

        # 2. Get diff
        diff_headers = {
            **self._headers(),
            "Accept": "application/vnd.github.v3.diff",
        }
        diff_resp = self._request_with_status_retry(
            "GET",
            pr_api_url,
            headers=diff_headers,
            context="fetch PR diff",
        )
        self._handle_error_status(diff_resp, "fetch PR diff")

        return PRInfo(
            platform="github",
            pr_id=(
                f"{self.owner}/{self.repo}#{self.pr_number}"
            ),
            pr_url=pr_url,
            title=data.get("title", ""),
            description=data.get("body", "") or "",
            diff=diff_resp.text,
            source_branch=(
                data.get("head", {}).get("ref", "")
            ),
            target_branch=(
                data.get("base", {}).get("ref", "")
            ),
            author=(
                data.get("user", {}).get("login", "")
            ),
            version_id=(
                data.get("head", {}).get("sha", "")
            ),
        )

    def post_comment(self, pr_url: str, comment: str) -> None:
        """Post a review comment on the GitHub PR."""
        self._check_credentials()

        comment_url = (
            f"{_GITHUB_API_BASE}/repos/"
            f"{self.owner}/{self.repo}"
            f"/issues/{self.pr_number}/comments"
        )

        body = comment

        resp = self._request_with_status_retry(
            "POST",
            comment_url,
            json={"body": body},
            context="post comment",
        )

        if not resp.is_success:
            raise CommentWriteBackError(
                f"Failed to post comment on GitHub PR "
                f"{self.owner}/{self.repo}"
                f"#{self.pr_number}: "
                f"HTTP {resp.status_code}"
            )
